- package-lock.json
- package.json
See https://github.com/eslint/eslint/issues/3458
BREAKING CHANGE: Plugins must now be installed as devDependencies.
> chore(deps): move plugins to peerDependencies

- rules/typescript.js
Passing object to @typescript-eslint/array-type rule otherwise eslint fails trying to load config,
since is expecting an object instead of an string.
fix #127
> fix(rules/typescript.js): fix @typescript-eslint/array-type rule

- package-lock.json
- package.json
- rules/typescript.js
To be able to use the `Array.sort` function we should ignore the magic number `-1`. This PR fixes that
> feat: ignore magic-number -1

- rules/typescript.js
Temporary disabling this rule as it blocks some repositories on required status checks.
> fix: disable naming conventions rule

- rules/typescript.js
This concerns rules added in  [v2.17.0](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/CHANGELOG.md#2170-2020-01-20) and [v2.18.0](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/CHANGELOG.md#2180-2020-01-27) of https://github.com/typescript-eslint/typescript-eslint/
> feat: add missing typescript-eslint rules

- rules/jest.js
- test/__snapshots__/index.spec.ts.snap
- test/fixtures/jest/prefer-expect-assertions.fail.ts
- test/fixtures/jest/prefer-expect-assertions.pass.ts
This is often useful when testing asynchronous code, in order to make sure that assertions in a callback actually got called but also for consistency across tests.
> chore: configure jest/prefer-expect-assertions

- rules/eslint.js
Disabling the native `init-declarations` as this has been replaced by `@typescript-eslint/init-declarations`.
The new `@typescript-eslint/init-declarations` is error and not warn tho.
> fix: disable native init-declarations rule

- rules/eslint.js
This rule is more often disabled in files than not. If it is not used then there is no value in having it enabled.
> feat: disable max-lines eslint rule

- .github/workflows/continuous-delivery.yaml
CI fails for chore(release) messages because the package is already published. This prevents a re-release.
As copied [from firestore-schema](https://github.com/ridedott/firestore-schema/blob/f177809df58540237afba82af4905b70e74616c0/.github/workflows/continuous-delivery.yaml#L10).
> feat: do not push a release in ci on chore release messages

- rules/eslint.js
- test/__snapshots__/index.spec.ts.snap
- test/fixtures/eslint/capitalized-comments.fail.ts
- test/fixtures/eslint/capitalized-comments.pass.ts
This also removes the usage of `// cspell ...` to enforce it as block comments.
> feat: ignore cspell and c8 block comments for capitalized-comments rule

- rules/import.js
This reverts commit 7cbf043d241f88a85f722b567f692662dab879cb.
I don't necessarily mean to revert the commit, but wanted to share my findings and maybe start the discussion. 
Like I [posted](https://ridedott.slack.com/archives/CDW5BKQJ1/p1629450455098700) in development-back-end channel, some recent change to `@ridedott/eslint-config` made Portal Lint check run [very slowly](https://github.com/ridedott/portal/pull/4160/checks?check_run_id=3382612441): going from ~2.2m to ~13-18m 😱  This looked like too big of a leap that could be caused by some @typescript-eslint double-parsing, so I decided to investigate more.
Running ESLint in profiling mode on my local machine revealed that the biggest part of it is `import/no-cycle` rule:
Before: ~35s After ~750s
I looked up the implementation of the …
> revert: perf: do not detect cycles in dependencies

- rules/import.js
- test/__snapshots__/index.spec.ts.snap
- test/fixtures/import/no-extraneous-dependencies.fail.ts
- test/fixtures/import/no-extraneous-dependencies.pass.ts
Currently it is possible to import a devDependency without any build errors.
It only pops out during runtime, like it happened with `payments-service`: https://cloudlogging.app.goo.gl/qyKLJNVRn8xfp1ze7
> feat: add import/no-extraneous-dependencies rule

- rules/import.js
Relates to https://github.com/ridedott/firestore-schema/pull/2690
Clearly `scripts` should also be allowed to use dev dependencies:
https://github.com/ridedott/firestore-schema/runs/4924459667?check_suite_focus=true
> feat: add more paths to ignore devDependencies usage

- test/__snapshots__/index.spec.ts.snap
- test/fixtures/@typescript-eslint/prefer-nullish-coalescing.fail.ts
- test/fixtures/unicorn/prefer-add-event-listener.pass.ts
- test/fixtures/unicorn/prefer-node-append.fail.ts
- test/fixtures/unicorn/prefer-node-append.pass.ts
- test/fixtures/unicorn/prefer-node-remove.fail.ts
- test/fixtures/unicorn/prefer-node-remove.pass.ts
- test/fixtures/unicorn/prefer-query-selector.fail.ts
- test/fixtures/unicorn/prefer-query-selector.pass.ts
At first I wanted to bump the TODOs like we usually do to unblock dependabot updates, but realized that I was the one who bumped them the last time, and it's been quite a while since they were created.
Test cases are inspired by the ones in the original repos for eslint-plugin-unicorn and typescript-eslint. Since we don't do any additional configuration for these specific rules, I assume there's no reason to add more test cases as they are covered in "parent" repos, and we just want to check that they're enabled.
I also found a few TODOs which are outdated but not reported and do not block dependabot, because the tests are actually not used, as these rules were removed a while ago: https://github.com/ridedott/eslint-config/commit/2de6a7306369976d8465efbe42b76e6070f40623#diff-eafbe97ee7fea4 …
> chore: add missing tests

- rules/typescript.js
- test/fixtures/@typescript-eslint/naming-convention.pass.ts
[Recently](https://github.com/ridedott/eslint-config/pull/1461) we updated `@typescript-eslint/eslint-plugin`, and that update included a [release](https://github.com/typescript-eslint/typescript-eslint/releases/tag/v5.14.0) where the behavior of `naming-convention` rule got [changed](https://github.com/typescript-eslint/typescript-eslint/pull/4582). Because of this, versions of `@ridedott/eslint-plugin` that came after are complaining about cases like this:
```
<span style=${styleMap({ 'background-color': 'red' })}>
```
because `background-color` is not written in camel case.
There's quite a lot of cases like this in frontend repos, usually it's specifying CSS class names in the code (which are usually dash-separated and not camel cased). It seems there's also quite a lot of similar …
> feat: allow different casing for properties requiring quotes

- rules/import.js
As the Service Health team is experimenting with [danger](https://github.com/danger/danger) (which requires us to add a devDependency as well as a TS file at the root of the project), our eslint config complains about the external dependencies being used.
This PR allows external dependencies inside the `dangerfile.ts`
> chore: all external dependencies from dangerfile

- .husky/commit-msg
- .husky/pre-commit
- README.md
- package.json
Makes sure that the Husky setup is working with v8 again.
Note: You need to run `npx husky install` as part of the setup after `npm install/ci`
> feat: update Husky setup

- package-lock.json
- package.json
Reverts 40959a36c1066a64b1ac5399546f910c9c625239.
> revert: chore(deps-dev): bump @types/node from 12.20.55 to 16.0.0

- .github/dependabot.yaml
The current ignore rule actually will only allow the @types/node 16.0.0 release and not one of the newer 16.x.x releases, which this should fix.
> chore: allow newest node 16 typings

- package-lock.json
- package.json
- test/index.spec.ts
Even though v8 is already released, to support ESLint's new flat configs, only v7 is required. Since v8 includes more changes to rules configuration, I suggest we update only to v7 for now, and tackle the remaining changes when we also update to flat config.
See [release post](https://typescript-eslint.io/blog/announcing-typescript-eslint-v7) for details.
> feat: update to typescript-eslint@7

- .vscode/settings.json
Jest was removed in https://github.com/ridedott/eslint-config/pull/2488, so this is no longer needed.
> chore: removed no longer used vscode setting

- index.js
- rules/unicorn.js
- test/__snapshots__/index.spec.ts.snap
- test/fixtures/@typescript-eslint/promise-function-async.pass.ts
- test/fixtures/@typescript-eslint/return-await.fail.ts
- test/fixtures/@typescript-eslint/return-await.pass.ts
- test/fixtures/eslint-comments/no-use.fail.ts
- test/fixtures/eslint/capitalized-comments.fail.ts
- test/fixtures/eslint/capitalized-comments.pass.ts
- test/fixtures/import/no-cycle.fail.ts
- test/fixtures/import/no-cycle/a.ts
- test/fixtures/simple-import-sort/imports.fail.ts
- test/fixtures/simple-import-sort/imports.pass.ts
- test/fixtures/unicorn/expiring-todo-comments.fail.ts
- test/fixtures/unicorn/expiring-todo-comments.pass.ts
- test/fixtures/unicorn/filename-case.pass.ts
- test/fixtures/unicorn/prefer-ternary.pass.ts
- test/fixtures/unicorn/prefer-top-level-await.pass.ts
To get the most out of the ESLint plugins we include, it's better if we extend recommended rules so that we get useful updates whenever they're extended. I reviewed our rule overrides to check which have the same configuration in the recommended config and removed these, left a few that are configured differently.
> feat: use recommended unicorn config

- rules/unicorn.js
`@typescript-eslint/switch-exhaustiveness-check` seems more useful to have, it already caught a few bugs in our codebases.
> fix: disable unicorn/no-useless-switch-case

- rules/unicorn.js
For both of these rules we have way more usages for the "not alllowed" option. The rules seem to be more on the stylistic preference side, so disabling them both.
> feat: disable unicorn/prefer-event-target

- rules/stylistic.js
I find this handy for consistency of inline documentation.
> feat: add comment length rule back

- configs/stylistic.js
- makeConfig.js
- test/__snapshots__/index.spec.ts.snap
- test/fixtures/@stylistic/max-len.fail.ts
- test/fixtures/@stylistic/max-len.pass.ts
- test/fixtures/@typescript-eslint/no-magic-numbers.fail.ts
- test/fixtures/@typescript-eslint/no-magic-numbers.pass.ts
- test/fixtures/import/no-extraneous-dependencies.fail.ts
- test/fixtures/import/no-extraneous-dependencies.pass.ts
- test/fixtures/unicorn/expiring-todo-comments.fail.ts
- test/fixtures/unicorn/expiring-todo-comments.pass.ts
- test/fixtures/unicorn/throw-new-error.fail.ts
- test/fixtures/unicorn/throw-new-error.pass.ts
- test/index.spec.ts
eslint-config-prettier overrides a whole bunch of stylistic rules, especially max-len which we don't want. I opted to move the stylistic rule under eslint-config-prettier. It's a little risky as there's a small chance that what prettier rewrites, creates a conflict with eslint. But I'm pretty sure that's not the case here, I double checked. If it does happen though we'll just come back here and resolve the conflicts.
I really prefer to have the max-len rule working correctly, and I couldn't find another way.
> feat: correctly set stylistic rules
